import { AgentMessage } from '@/types';

// ===== CONFIGURATION =====
// Supports any OpenAI-compatible API (Kimi, MiMo, CanopyWave, OpenRouter, etc.)
const API_BASE_URL = process.env.API_BASE_URL || '';
const API_KEY = process.env.API_KEY || '';
const USE_MOCK = !API_KEY || API_KEY === 'demo' || API_KEY === 'your_api_key_here';

export interface LLMConfig {
  model: string;
  temperature?: number;
  max_tokens?: number;
  stream?: boolean;
}

export const MODELS = {
  // MiMo models (use these when you get MiMo API key)
  MIMO_PRO: 'mimo-v2-pro',
  MIMO_OMNI: 'mimo-v2-omni',
  MIMO_TTS: 'mimo-v2-tts',
  MIMO_FLASH: 'mimo-v2-flash',

  // CanopyWave models (current provider)
  CANOPY_KIMI_K2_6: 'moonshotai/kimi-k2.6',
} as const;

// Current active model - change this when you switch providers
export const ACTIVE_MODEL = process.env.ACTIVE_MODEL || MODELS.CANOPY_KIMI_K2_6;

// ===== MOCK RESPONSES (Fallback when no API key) =====
function getMockResponse(messages: AgentMessage[], config: LLMConfig): string {
  const userMessage = messages.find(m => m.role === 'user')?.content || '';
  
  if (userMessage.toLowerCase().includes('plan') || userMessage.includes('研究计划')) {
    return `# Research Plan

## Objectives
1. Gather comprehensive information on the query topic
2. Identify key stakeholders and their perspectives
3. Analyze current trends and future implications
4. Evaluate conflicting viewpoints

## Methodology
- Multi-source information extraction
- Cross-reference verification
- Chain-of-thought reasoning
- Structured synthesis

## Expected Output
A comprehensive report with executive summary, key findings, and actionable recommendations.`;
  }
  
  if (userMessage.toLowerCase().includes('extract') || userMessage.includes('提取')) {
    return `## Extracted Information

### Key Facts
- The topic involves multiple interconnected domains
- Recent developments show accelerating trends
- Stakeholder opinions vary significantly across regions

### Data Points
- Market size estimated at $50B+ annually
- Growth rate: 15-20% CAGR
- Primary adoption in North America and Asia-Pacific

### Sources Analyzed
- Academic papers (23 sources)
- Industry reports (8 sources)
- News articles (45 sources)
- Expert interviews (simulated)`;
  }
  
  if (userMessage.toLowerCase().includes('reason') || userMessage.includes('推理')) {
    return `## Reasoning Analysis

### Step 1: Problem Decomposition
Breaking down the complex query into manageable components...

### Step 2: Pattern Recognition
Identifying recurring themes across sources:
- Theme A: Technological advancement driving change
- Theme B: Regulatory frameworks lagging behind innovation
- Theme C: Economic implications vary by sector

### Step 3: Causal Analysis
Primary drivers → Secondary effects → Tertiary implications

### Step 4: Verification
Cross-checking claims against multiple sources...
- Claim 1: Verified (8/10 sources agree)
- Claim 2: Partially verified (mixed evidence)
- Claim 3: Requires further investigation

### Conclusion
The analysis reveals a complex landscape with both opportunities and challenges. Key recommendations emerge from the intersection of technological capability and market readiness.`;
  }
  
  if (userMessage.toLowerCase().includes('report') || userMessage.includes('报告')) {
    return `# Research Report

## Executive Summary
Based on comprehensive multi-agent analysis, this report examines the query topic through multiple lenses. The findings indicate significant transformative potential with important caveats.

## Key Findings

### 1. Market Landscape
The current market demonstrates robust growth with increasing competitive intensity. Key players are investing heavily in R&D, driving innovation cycles shorter than historical norms.

### 2. Technical Capabilities
Modern approaches leverage advanced AI models to achieve previously impossible results. Multimodal understanding enables comprehensive analysis across text, image, and video sources.

### 3. Challenges and Risks
- Regulatory uncertainty in key markets
- Technical limitations in edge cases
- Adoption barriers for non-technical users

### 4. Future Outlook
The next 3-5 years will likely see:
- Consolidation of market leaders
- Standardization of best practices
- Emergence of new application domains

## Recommendations

1. **Immediate Actions**: Focus on building robust evaluation frameworks
2. **Short-term Strategy**: Develop partnerships with key technology providers
3. **Long-term Vision**: Invest in fundamental research for sustainable competitive advantage

## Conclusion
The intersection of advanced AI capabilities and market demand creates a compelling opportunity. Success requires careful navigation of technical, regulatory, and competitive challenges.

---
*Generated by Cerebrum Multi-Agent Research System*`;
  }
  
  return `Analysis complete. The research indicates complex interdependencies requiring careful consideration of multiple factors. Key insights have been synthesized from diverse sources using advanced reasoning techniques.`;
}

async function* mockStreamResponse(messages: AgentMessage[], config: LLMConfig): AsyncGenerator<string> {
  const response = getMockResponse(messages, config);
  const words = response.split(' ');
  
  for (let i = 0; i < words.length; i += 3) {
    const chunk = words.slice(i, i + 3).join(' ') + ' ';
    yield chunk;
    await new Promise(resolve => setTimeout(resolve, 30));
  }
}

// ===== REAL API CLIENT =====
export async function* streamCompletion(
  messages: AgentMessage[],
  config: LLMConfig
) {
  if (USE_MOCK) {
    yield* mockStreamResponse(messages, config);
    return;
  }

  if (!API_BASE_URL) {
    throw new Error(
      'API_BASE_URL is not configured. Please set it in your environment variables (e.g., https://api.canopywave.com/v1).'
    );
  }

  const response = await fetch(`${API_BASE_URL}/chat/completions`, {
    method: 'POST',
    headers: {
      'Content-Type': 'application/json',
      'Authorization': `Bearer ${API_KEY}`,
    },
    body: JSON.stringify({
      model: config.model || ACTIVE_MODEL,
      messages,
      temperature: config.temperature ?? 0.7,
      max_tokens: config.max_tokens ?? 4096,
      stream: true,
    }),
  });

  if (!response.ok) {
    const errorText = await response.text();
    throw new Error(`API error ${response.status}: ${errorText}`);
  }

  const reader = response.body?.getReader();
  if (!reader) throw new Error('No response body');

  const decoder = new TextDecoder();
  let buffer = '';

  while (true) {
    const { done, value } = await reader.read();
    if (done) break;

    buffer += decoder.decode(value, { stream: true });
    const lines = buffer.split('\n');
    buffer = lines.pop() || '';

    for (const line of lines) {
      if (line.trim() === '' || line.trim() === 'data: [DONE]') continue;
      if (line.startsWith('data: ')) {
        try {
          const data = JSON.parse(line.slice(6));
          const content = data.choices?.[0]?.delta?.content;
          if (content) yield content;
        } catch {
          // Skip malformed lines
        }
      }
    }
  }
}

export async function completion(
  messages: AgentMessage[],
  config: LLMConfig
): Promise<string> {
  if (USE_MOCK) {
    return getMockResponse(messages, config);
  }

  if (!API_BASE_URL) {
    throw new Error(
      'API_BASE_URL is not configured. Please set it in your environment variables (e.g., https://inference.canopywave.io/v1).'
    );
  }

  const response = await fetch(`${API_BASE_URL}/chat/completions`, {
    method: 'POST',
    headers: {
      'Content-Type': 'application/json',
      'Authorization': `Bearer ${API_KEY}`,
    },
    body: JSON.stringify({
      model: config.model || ACTIVE_MODEL,
      messages,
      temperature: config.temperature ?? 0.7,
      max_tokens: config.max_tokens ?? 4096,
      stream: false,
    }),
  });

  if (!response.ok) {
    const errorText = await response.text();
    throw new Error(`API error ${response.status}: ${errorText}`);
  }

  const data = await response.json();
  return data.choices?.[0]?.message?.content || '';
}

// ===== BACKWARDS COMPATIBILITY =====
export const MIMO_MODELS = MODELS;
export async function* streamMimoCompletion(messages: AgentMessage[], config: LLMConfig) {
  return yield* streamCompletion(messages, config);
}
export async function mimoCompletion(messages: AgentMessage[], config: LLMConfig) {
  return completion(messages, config);
}
