'use client';

import { useState } from 'react';
import { motion, AnimatePresence } from 'framer-motion';
import { Download, FileText, Code, X, Loader2 } from 'lucide-react';

interface ExportModalProps {
  isOpen: boolean;
  onClose: () => void;
  report: string;
  query: string;
}

export default function ExportModal({ isOpen, onClose, report, query }: ExportModalProps) {
  const [exporting, setExporting] = useState<string | null>(null);

  const safeName = query.replace(/[^a-zA-Z0-9\u4e00-\u9fff\s-]/g, '').trim().slice(0, 50) || 'research';
  const fileName = `cerebrum-${safeName.replace(/\s+/g, '-').toLowerCase()}-${Date.now()}`;

  const downloadMarkdown = () => {
    setExporting('md');
    const blob = new Blob([report], { type: 'text/markdown' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `${fileName}.md`;
    a.click();
    URL.revokeObjectURL(url);
    setTimeout(() => setExporting(null), 500);
  };

  const downloadHTML = () => {
    setExporting('html');
    // Convert markdown to styled HTML
    const html = `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>${query} — Cerebrum Research</title>
  <style>
    * { margin: 0; padding: 0; box-sizing: border-box; }
    body {
      font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif;
      line-height: 1.7; color: #1a1a2e; max-width: 800px; margin: 0 auto;
      padding: 40px 20px; background: #fafafa;
    }
    h1 { font-size: 28px; margin-bottom: 8px; color: #0a0a0a; border-bottom: 2px solid #22c55e; padding-bottom: 12px; }
    h2 { font-size: 22px; margin: 32px 0 12px; color: #166534; }
    h3 { font-size: 18px; margin: 24px 0 8px; color: #15803d; }
    p { margin: 8px 0; }
    ul, ol { margin: 8px 0 8px 24px; }
    li { margin: 4px 0; }
    strong { color: #166534; }
    a { color: #2563eb; text-decoration: none; }
    a:hover { text-decoration: underline; }
    blockquote { border-left: 3px solid #22c55e; padding-left: 16px; margin: 16px 0; color: #555; }
    code { background: #f0f0f0; padding: 2px 6px; border-radius: 4px; font-size: 14px; }
    pre { background: #1a1a2e; color: #e0e0e0; padding: 16px; border-radius: 8px; overflow-x: auto; margin: 16px 0; }
    hr { border: none; border-top: 1px solid #e0e0e0; margin: 32px 0; }
    .header { text-align: center; margin-bottom: 32px; }
    .footer { text-align: center; margin-top: 48px; padding-top: 24px; border-top: 1px solid #e0e0e0; color: #888; font-size: 13px; }
  </style>
</head>
<body>
  <div class="header">
    <h1>${query}</h1>
    <p style="color: #666; font-size: 14px;">Generated by Cerebrum Multi-Agent Research System</p>
  </div>
  <div id="content">${simpleMarkdownToHTML(report)}</div>
  <div class="footer">
    <p>Powered by Cerebrum — Multi-Agent Research System</p>
  </div>
</body>
</html>`;

    const blob = new Blob([html], { type: 'text/html' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `${fileName}.html`;
    a.click();
    URL.revokeObjectURL(url);
    setTimeout(() => setExporting(null), 500);
  };

  const downloadJSON = () => {
    setExporting('json');
    const data = {
      query,
      report,
      timestamp: new Date().toISOString(),
      wordCount: report.split(/\s+/).length,
      readingTime: Math.ceil(report.split(/\s+/).length / 200),
    };
    const blob = new Blob([JSON.stringify(data, null, 2)], { type: 'application/json' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `${fileName}.json`;
    a.click();
    URL.revokeObjectURL(url);
    setTimeout(() => setExporting(null), 500);
  };

  return (
    <AnimatePresence>
      {isOpen && (
        <>
          {/* Backdrop */}
          <motion.div
            initial={{ opacity: 0 }}
            animate={{ opacity: 1 }}
            exit={{ opacity: 0 }}
            onClick={onClose}
            className="fixed inset-0 bg-black/60 backdrop-blur-sm z-50"
          />

          {/* Modal */}
          <motion.div
            initial={{ opacity: 0, scale: 0.95, y: 20 }}
            animate={{ opacity: 1, scale: 1, y: 0 }}
            exit={{ opacity: 0, scale: 0.95, y: 20 }}
            className="fixed top-1/2 left-1/2 -translate-x-1/2 -translate-y-1/2 z-50 w-full max-w-md"
          >
            <div className="glass-strong rounded-2xl p-6 border border-white/[0.06] shadow-2xl">
              <div className="flex items-center justify-between mb-5">
                <h3 className="text-lg font-semibold text-gray-200">Export Report</h3>
                <button onClick={onClose} className="p-1.5 rounded-lg hover:bg-white/[0.04] text-gray-400 hover:text-white transition-colors">
                  <X className="w-4 h-4" />
                </button>
              </div>

              <div className="space-y-3">
                <ExportOption
                  icon={<FileText className="w-5 h-5" />}
                  title="Markdown (.md)"
                  desc="Plain text with formatting — universal, lightweight"
                  onClick={downloadMarkdown}
                  loading={exporting === 'md'}
                  color="text-green-400"
                />
                <ExportOption
                  icon={<Code className="w-5 h-5" />}
                  title="HTML (.html)"
                  desc="Styled web page — ready to view in any browser"
                  onClick={downloadHTML}
                  loading={exporting === 'html'}
                  color="text-blue-400"
                />
                <ExportOption
                  icon={<Download className="w-5 h-5" />}
                  title="JSON (.json)"
                  desc="Structured data — for programmatic use"
                  onClick={downloadJSON}
                  loading={exporting === 'json'}
                  color="text-purple-400"
                />
              </div>
            </div>
          </motion.div>
        </>
      )}
    </AnimatePresence>
  );
}

function ExportOption({ icon, title, desc, onClick, loading, color }: {
  icon: React.ReactNode; title: string; desc: string; onClick: () => void; loading: boolean; color: string;
}) {
  return (
    <button
      onClick={onClick}
      disabled={loading}
      className="w-full flex items-center gap-4 p-4 rounded-xl bg-white/[0.02] border border-white/[0.04] hover:border-green-500/20 hover:bg-white/[0.04] transition-all text-left group"
    >
      <div className={`${color} opacity-70 group-hover:opacity-100 transition-opacity`}>
        {loading ? <Loader2 className="w-5 h-5 animate-spin" /> : icon}
      </div>
      <div>
        <p className="text-sm font-medium text-gray-300">{title}</p>
        <p className="text-[11px] text-gray-500">{desc}</p>
      </div>
    </button>
  );
}

/** Simple markdown to HTML converter for export */
function simpleMarkdownToHTML(md: string): string {
  let html = md
    // Escape HTML
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    // Headers
    .replace(/^### (.+)$/gm, '<h3>$1</h3>')
    .replace(/^## (.+)$/gm, '<h2>$1</h2>')
    .replace(/^# (.+)$/gm, '<h1>$1</h1>')
    // Bold and italic
    .replace(/\*\*(.+?)\*\*/g, '<strong>$1</strong>')
    .replace(/\*(.+?)\*/g, '<em>$1</em>')
    // Links
    .replace(/\[([^\]]+)\]\(([^)]+)\)/g, '<a href="$2" target="_blank">$1</a>')
    // Inline code
    .replace(/`([^`]+)`/g, '<code>$1</code>')
    // Horizontal rule
    .replace(/^---$/gm, '<hr>')
    // Unordered list items
    .replace(/^[-*] (.+)$/gm, '<li>$1</li>')
    // Paragraphs (double newline)
    .replace(/\n\n/g, '</p><p>')
    // Single newline to <br>
    .replace(/\n/g, '<br>');

  // Wrap list items
  html = html.replace(/(<li>[\s\S]*?<\/li>)/g, '<ul>$1</ul>');
  // Clean up nested ul
  html = html.replace(/<\/ul><br><ul>/g, '');

  return `<p>${html}</p>`;
}
